baseURL = "http://mirrors.hexang.com/site/"
theme = "dot"
languageCode = "zh_CN"
defaultContentLanguage = "zh"

[params]
primaryColor = "#263130"
secondaryColor = "#f9f9f9"
textColor = "#636363"
textColorDark = "#242738"
whiteColor = "#f4f4f4"

[Languages]


      # Simple Chinese Language
      [Languages.zh]
#      languageName = "简体中文"
      weight = 1
      languageCode = "zh_CN"
      title = "hexang 开源镜像站"
      dateFormat = "2 January 2006"
      home = "主页"
      logo = "HEXANG"
      copyright = "hexang.org 2018-2019"

        # navigation
        [Languages.zh.menu]

          [[Languages.zh.menu.main]]
            weight = 2
            name = "镜像站新闻"
            url = "/news"

          [[Languages.zh.menu.main]]
            weight = 2
            name = "常见问题"
            url = "/faq"

          [[Languages.zh.menu.main]]
            weight = 2
            name = "联系我们"
            url = "/contact"

          # [[Languages.zh.menu.main]]
          #   weight = 2
          #   name = "相关页面"
          #   url = "/pages"
          #   hasChildren = true
          #
          #     [[Languages.zh.menu.main]]
          #     parent = "相关页面"
          #     name = "Elements"
          #     URL = "/elements"
          #     weight = 1
          #
          #     [[Languages.zh.menu.main]]
          #     parent = "相关页面"
          #     name = "Installation"
          #     URL = "/installation"
          #     weight = 1
          #
          #     [[Languages.zh.menu.main]]
          #     parent = "相关页面"
          #     name = "Billing and Pricing"
          #     URL = "/pypi"
          #     weight = 2
          #
          #     [[Languages.zh.menu.main]]
          #     parent = "相关页面"
          #     name = "Features"
          #     URL = "/features"
          #     weight = 3




        # banner
        [Languages.zh.params.banner]
          title = "息壤开源镜像站"
          description = "专注生产力工具解决方案"
          image = "images/banner.jpg"
          placeholder = "您需要什么工具,请在此搜索..."

        # Topics
        [Languages.zh.params.topics]
          title = "在此寻找..."

        # call to action
        [Languages.zh.params.cta]
          enable = true
          title = "没找到所需的工具?请联系我们!"
          description = "我们将根据相关项目的许可来决定是否添加"
          btnText = "联系我们"
          btnURL = "/contact"

        # contact
        [Languages.zh.params.contact]
          title = "有任何问题?"
          content = ""

        # footer social icon
        [[Languages.zh.socialIcon]]
          icon = "ti-github"
          URL = "/#"

        [[Languages.zh.socialIcon]]
          icon = "ti-email"
          URL = "/#"
